# .gitlab/agents/stuXX/config.yaml

###### for gitlab-<labber>-lab #####
user_access:
  access_as:
    agent: {}
  projects:
    - id: <gitlab_project_or_id>/gitlab-bg-lab  # ğŸ³  Change this 

ci_access:
  projects:
    - id: <gitlab_project_or_id>/gitlab-bg-lab  # ğŸ³  Change this 